name: ci

on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker-compose -f docker-compose-build.yaml build --parallel
      - run: docker tag udagram-api-feed:v1 kidoti/udagram-api-feed:v1
      - run: docker tag udagram-api-user:v1 kidoti/udagram-api-user:v1
      - run: docker tag udagram-frontend:local kidoti/udagram-frontend:v2
      - run: docker tag reverseproxy:v1 kidoti/reverseproxy:v1
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push kidoti/udagram-api-feed:v1
      - run: docker push kidoti/udagram-api-user:v1
      - run: docker push kidoti/udagram-frontend:v2
      - run: docker push kidoti/reverseproxy:v1
